// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8pdsSOa_wiESi1QUUUVw-4JLLa3GBS8',
    appId: '1:278501172745:web:f3cd35144a7f1c1cb2bad8',
    messagingSenderId: '278501172745',
    projectId: 'volunteerapp-2f55a',
    authDomain: 'volunteerapp-2f55a.firebaseapp.com',
    storageBucket: 'volunteerapp-2f55a.appspot.com',
    measurementId: 'G-XHDKFZ28XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf040IkTNnFIvJ7MnXhm6C_fOfyx-c_74',
    appId: '1:278501172745:android:6116f68804987618b2bad8',
    messagingSenderId: '278501172745',
    projectId: 'volunteerapp-2f55a',
    storageBucket: 'volunteerapp-2f55a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmIrLlxsBWYVh8u34D4jknjBa9oe3gi4',
    appId: '1:278501172745:ios:77c0bd1fb9258b8db2bad8',
    messagingSenderId: '278501172745',
    projectId: 'volunteerapp-2f55a',
    storageBucket: 'volunteerapp-2f55a.appspot.com',
    iosBundleId: 'com.example.volunteering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkmIrLlxsBWYVh8u34D4jknjBa9oe3gi4',
    appId: '1:278501172745:ios:66ef9fb15f7380b4b2bad8',
    messagingSenderId: '278501172745',
    projectId: 'volunteerapp-2f55a',
    storageBucket: 'volunteerapp-2f55a.appspot.com',
    iosBundleId: 'com.example.volunteering.RunnerTests',
  );
}
